"""
Day 4 synthetic scenario tests.

The expected values in ScenarioSpec are independent ground truth.
They are NOT generated by calling the reconciliation engine.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "reconciliation-engine"))

from engine import compute_variance
from rate_card_loader import RateCardStore
from scenarios import SCENARIOS, generate_all_scenarios


STORE = RateCardStore()


def test_day4_has_nine_seeded_scenarios():
    assert len(SCENARIOS) == 9
    assert len({scenario.scenario_id for scenario in SCENARIOS}) == 9


def test_day4_generator_is_deterministic():
    first = generate_all_scenarios()
    second = generate_all_scenarios()

    assert first == second

    for spec, transaction, settlement in first:
        assert transaction.transaction_id == f"TX-{spec.scenario_id}"
        assert settlement.settlement_id == f"SET-{spec.scenario_id}"
        assert settlement.transaction_id == transaction.transaction_id


def test_day4_engine_matches_independent_ground_truth():
    """
    Every seeded scenario must produce exactly the independently specified
    expected fee, variance, and exception flag.
    """
    results = []

    for spec, transaction, settlement in generate_all_scenarios():
        result = compute_variance(
            transaction,
            actual_fee_ngn=settlement.actual_fee_ngn,
            store=STORE,
        )

        assert result.expected_fee_ngn == spec.expected_fee_ngn, spec.scenario_id
        assert result.variance_ngn == spec.expected_variance_ngn, spec.scenario_id
        assert result.flagged == spec.expected_flagged, spec.scenario_id

        results.append(result)

    assert len(results) == 9


def test_day4_ground_truth_detection_has_zero_false_results():
    """
    Ground-truth detection is exact:
    every planted exception is flagged and every clean scenario remains clean.
    """
    false_negatives = []
    false_positives = []

    for spec, transaction, settlement in generate_all_scenarios():
        result = compute_variance(
            transaction,
            actual_fee_ngn=settlement.actual_fee_ngn,
            store=STORE,
        )

        if spec.expected_flagged and not result.flagged:
            false_negatives.append(spec.scenario_id)

        if not spec.expected_flagged and result.flagged:
            false_positives.append(spec.scenario_id)

    assert false_negatives == []
    assert false_positives == []
